### ISSUE TITLE
需求：思源笔记新增了数据库属性，希望插件可以支持

### ISSUE THREAD

**Issue by zzz51522** [InEase/SiYuan-Attributes-Panel#2]
目前在插件面板无法新增数据库中的属性，希望可以支持。
如果可以实现，那么 数据库+属性面板插件 将完美复刻Notion

https://github.com/InEase/SiYuan-Attributes-Panel/assets/145221733/593f03e5-eb8c-44ab-ac70-06305f3e9d95

**Comment by QMike0** [comment]
+1强烈支持显示`数据库属性`
思源中的`内置属性`仅仅显示`别名`、`命名`、`书签`等内容，这些内容基本上已经在文档右上角显示，可以直接查看，感觉其实没有另外展示的必要：
![image](https://github.com/InEase/SiYuan-Attributes-Panel/assets/43239563/941df697-9726-4eab-aa99-7363dcedb774)
而`自定义属性`则被设计用来修改特定文档的属性（例如修改文档内容样式）等，并被很多插件用于标记文档以实现相应的功能，并非普通用户需要频繁查看的内容
> 我个人基本上不查看和修改自定义属性中的内容，除非需要使用CSS代码片段修改特定文档的样式，才会在这里面添加对应的属性值。大多数人应该也是如此

`数据库属性`则是用户自定义的属性内容，肯定会成为用于内容块（特别是文档）分类的重要依据，而官方在文档层面没有提供清晰直观的可视化方式（添加数据库属性的文档，只有右上角有个小块标，需要点击后跳转属性界面查看，特别不方便）。
![image](https://github.com/InEase/SiYuan-Attributes-Panel/assets/43239563/1248f2be-2df8-4639-b4a5-ca35924bfc0a)


大佬假如能让这个插件支持`数据库属性`的显示就太感谢了，这样基本上就和notion的显示方式一致
> PS：个人觉得不显示文档的`内置属性`和`自定义属性`、只显示`数据库属性`，也无伤大雅；假如方便的话，可以提供一下显示这三类属性中哪一类或哪几类的切换按钮

**Comment by InEase** [comment]
感谢两位

**Comment by InEase** [comment]
> 思源中的内置属性仅仅显示别名、命名、书签等内容，这些内容基本上已经在文档右上角显示，可以直接查看，感觉其实没有另外展示的必要

对的，这里有点冗余，特别是属性面板还是挺占地方的，所以后面会开放用户自定义 #5

**Comment by InEase** [comment]
> PS：个人觉得可以不显示文档的内置属性和自定义属性、只显示数据库属性，这样也无伤大雅；假如方便的话，可以提供一下显示这三类属性中哪一类或哪几类的切换按钮。贴一张现在同时显示内置属性和自定义属性的界面，由于不止一个插件在该文档自定义属性中留下“痕迹”，真正有用的信息就很少

没问题，那看来后面的重点一个是数据库对接，一个是属性显示的设置了
