### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by TinkMingKing** [InEase/SiYuan-Attributes-Panel#3]
1. 屏蔽**所有**自定义属性的显示，例如：如图中的折叠属性，以及`custom-sy-readonly`这个文档只读属性等（自定义属性无需被用户关心）
![image](https://github.com/InEase/SiYuan-Attributes-Panel/assets/32903588/2398b9c8-51ba-46f2-9f62-b3fa9b0dd8d7)
2. 添加创建时间的属性显示
3. 支持内置属性和**数据库属性**的显示，如：增加开关，普通文档是否显示属性的开关，数据库显示数据库属性的开关，数据库显示内置属性的开关，数据库属性和内置属性稍微区分一点显示等等
4. `块ID`属性改成`文档ID`或者`文档块ID`会更好，建议是`文档ID`，也可以干脆不显示，或者支持点击复制，并添加开关是否显示该属性，内置属性的显示与否都可以加个开关让用户选择
5. 优化属性的显示顺序，或者也让用户自定义

**Comment by InEase** [comment]
感谢提议，1，2，4，5

**Comment by InEase** [comment]
关于设置，在这里一起讨论吧～感谢提议！ #5
