### ISSUE TITLE
文字显示会超过边框

### ISSUE THREAD

**Issue by lisontowind** [InEase/SiYuan-Attributes-Panel#6]
![image](https://github.com/InEase/SiYuan-Attributes-Panel/assets/47842345/68c87987-fac6-4d1e-acb4-7d78b65f5fc2)

**Comment by InEase** [comment]
感谢指出，目前只是最初的版本，后面会持续改进。类似这些内置属性其实直接隐藏也是可以的，后续也会通过设置面板，供用户自由选择显示方法。在 #5 这里一起讨论吧～ 我先关闭了，如果后续有需求可以继续新开issue～

**Comment by InEase** [comment]
目前开发重点在 #4 数据库这里，估计这周可以完成，设置快的话这周也能完成
