### ISSUE TITLE
安卓手机端伺服，显示不兼容

### ISSUE THREAD

**Issue by luo-chuan** [InEase/SiYuan-Attributes-Panel#8]
如图。安卓思源已是当前最新版2.12.2。
![图片](https://github.com/InEase/SiYuan-Attributes-Panel/assets/33930736/d879b25d-0718-4b31-a1d4-8fe1382b9441)

**Comment by InEase** [comment]
嘶, 诶, 这个场景有点刁钻, 网页版应该都是兼容的, 我等下研究一下嗷~ 感谢

**Comment by InEase** [comment]
在v1.1.1支持，麻烦多多关注，欢迎提交bug，感谢

**Comment by luo-chuan** [comment]
> 在v1.1.1支持，麻烦多多关注，欢迎提交bug，感谢

已升级1.1.1，我这里还是同样的问题，也重启过思源，麻烦再测试一下呢。是安卓手机作为伺服端。

**Comment by luo-chuan** [comment]
要兼容手机伺服，一是要在plugin.json的backends加上android，二是要在frontends加上browser-desktop。
关于plugin.json各设置项的详细定义看这里： https://github.com/siyuan-note/plugin-sample/blob/main/README_zh_CN.md

**Comment by InEase** [comment]
> 要兼容手机伺服，一是要在plugin.json的backends加上android，二是要在frontends加上browser-desktop。 关于plugin.json各设置项的详细定义看这里： https://github.com/siyuan-note/plugin-sample/blob/main/README_zh_CN.md

感谢, 我再研究一下

**Comment by TransMux** [comment]
非常感谢, v1.1.2加上啦! 感谢指出!
